version: '3.8'
services:
  app:
    image: characters-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - h2

networks:
  app-network:
    driver: bridge
